core:
  - changed-files:
      - any-glob-to-any-file:
          - packages/gensx/**

package:
  - changed-files:
      - any-glob-to-any-file:
          - packages/gensx-*/**

docs:
  - changed-files:
      - any-glob-to-any-file:
          - docs/**

examples:
  - changed-files:
      - any-glob-to-any-file:
          - examples/**
