name: "💅 Lint and Format"

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛬
        uses: actions/checkout@v4
      - name: Setup Node ⚙️
        uses: ./.github/actions/setup-node
        with:
          version: 20.x

      - name: Lint code 💅
        run: pnpm lint:all
      - name: Format code 📝
        run: pnpm format:check
