name: "🚀 Release Please"

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.PAT_GITHUB_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
      - name: Checkout 🛬
        if: ${{ steps.release.outputs.releases_created }}
        uses: actions/checkout@v4
      - name: Create package-specific tags 🏷️
        if: ${{ steps.release.outputs.releases_created }}
        run: |
          if [[ "${{ steps.release.outputs.gensx--release_created }}" == "true" ]]; then
            git tag "gensx@${{ steps.release.outputs.gensx--version }}"
            git push origin "gensx@${{ steps.release.outputs.gensx--version }}"
          fi
          if [[ "${{ steps.release.outputs['packages/gensx-openai--release_created'] }}" == "true" ]]; then
            git tag "@gensx/openai@${{ steps.release.outputs['packages/gensx-openai--version'] }}"
            git push origin "@gensx/openai@${{ steps.release.outputs['packages/gensx-openai--version'] }}"
          fi
      - name: Setup Node ⚙️
        if: ${{ steps.release.outputs.releases_created }}
        uses: ./.github/actions/setup-node
        with:
          npm_token: ${{ secrets.NPM_TOKEN }}
      - name: Cache turbo build setup
        if: ${{ steps.release.outputs.releases_created }}
        uses: actions/cache@v3
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-
      - name: Build Packages 🏗️
        if: ${{ steps.release.outputs.releases_created }}
        run: |
          pnpm install --frozen-lockfile
          pnpm turbo run build
      - name: Publish to NPM 🚀
        if: ${{ steps.release.outputs.releases_created }}
        run: |
          for pkg in $(pnpm recursive list --only-projects --json | jq -r '.[].name'); do
            if [[ "$pkg" != "@gensx-examples/"* ]]; then
              echo "Publishing $pkg"
              cd "packages/$(echo $pkg | sed 's/@gensx\///')"
              pnpm publish --no-git-checks --access public
              cd ../..
            fi
          done
