name: "🚀 Release Please"

on:
  push:
    branches:
      - main
  workflow_dispatch:

# Ensure this workflow has the necessary permissions
permissions:
  contents: write
  pull-requests: write
  id-token: write # needed for npm provenance

jobs:
  release-please:
    runs-on: ubuntu-latest
    # Only run on pushes to the original repository and not on forks
    if: |
      github.repository == 'cortexclick/gensx' &&
      github.event.repository.fork == false &&
      github.actor != 'dependabot[bot]'

    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.PAT_GITHUB_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

      # The following steps only run when merging a release PR
      - name: Checkout 🛬
        if: ${{ steps.release.outputs.releases_created }}
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Create package-specific tags 🏷️
        if: ${{ steps.release.outputs.releases_created }}
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          if [[ "${{ steps.release.outputs.gensx--release_created }}" == "true" ]]; then
            git tag "gensx@${{ steps.release.outputs.gensx--version }}"
            git push origin "gensx@${{ steps.release.outputs.gensx--version }}"
          fi
          if [[ "${{ steps.release.outputs['packages/gensx-openai--release_created'] }}" == "true" ]]; then
            git tag "@gensx/openai@${{ steps.release.outputs['packages/gensx-openai--version'] }}"
            git push origin "@gensx/openai@${{ steps.release.outputs['packages/gensx-openai--version'] }}"
          fi

      - name: Setup Node ⚙️
        if: ${{ steps.release.outputs.releases_created }}
        uses: ./.github/actions/setup-node
        with:
          npm_token: ${{ secrets.NPM_TOKEN }}

      - name: Build Packages 🏗️
        if: ${{ steps.release.outputs.releases_created }}
        run: |
          pnpm install --frozen-lockfile
          pnpm turbo run build

      - name: Publish to NPM 🚀
        if: ${{ steps.release.outputs.releases_created }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: "true"
        run: |
          pnpm publish --no-git-checks --access public -r
