name: "🐢 Lint and Test"

on:
  pull_request:
    branches: [main]
    paths:
      - "packages/**/*"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [22.x, 20.x, 18.x]

    steps:
      - name: Checkout 🛬
        uses: actions/checkout@v4
      - name: Setup Node ⚙️
        uses: ./.github/actions/setup-node
        with:
          version: ${{ matrix.node-version }}
          npm_token: ${{ secrets.NPM_TOKEN }}
      - name: Build 📦
        run: pnpm build
      - name: Lint code 💅
        run: pnpm lint
      - name: Run tests ✅
        run: pnpm test
