name: "🐢 Test and Build Packages"

on:
  pull_request:
    branches: [main]
    paths:
      - "packages/**/*"
  push:
    branches: [main]
    paths:
      - "packages/**/*"

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [22.x, 20.x, 18.x]

    steps:
      - name: Checkout 🛬
        uses: actions/checkout@v4
      - name: Setup Node ⚙️
        uses: ./.github/actions/setup-node
        with:
          version: ${{ matrix.node-version }}

      - name: Run tests 🧪
        run: pnpm test

      - name: Report GenSX Coverage 📊
        if: github.event_name == 'pull_request' && matrix.node-version == '20.x'
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          working-directory: packages/gensx
          vite-config-path: vitest.config.ts

      - name: Build 📦
        run: pnpm build
