name: "🐢 Lint and Test Examples"

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches: [main]
    paths:
      - "examples/**/*"
  push:
    branches: [main]
    paths:
      - "examples/**/*"

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    # Important security check for pull_request_target
    if: |
      (github.event_name == 'push') ||
      (github.event_name == 'pull_request_target' && github.event.pull_request.head.repo.full_name == github.repository)

    steps:
      - name: Checkout 🛬
        uses: actions/checkout@v4
        with:
          # Important: For PR events, explicitly checkout the PR HEAD
          ref: ${{ github.event_name == 'pull_request_target' && format('refs/pull/{0}/head', github.event.pull_request.number) || github.ref }}
          persist-credentials: false
      - name: Setup Node ⚙️
        uses: ./.github/actions/setup-node
        with:
          version: 22.x
          npm_token: ${{ secrets.NPM_TOKEN }}
      - name: Build 📦
        run: pnpm build:examples
      - name: Lint code 💅
        run: pnpm lint:examples
      - name: Format code 📝
        run: pnpm format:check
      - name: Run tests ✅
        run: pnpm test:examples
